## model 
model_name_or_path: /projects/vig/tangri/QwenMem/LLaMA-Factory/models/Qwen2_5_VL-3B-WithMemory
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

## method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: [
  "q_proj", "k_proj", "v_proj", "o_proj",
  "gate_proj", "up_proj", "down_proj",
  "memory.memory_to_language_mlp.0", "memory.memory_to_language_mlp.2",
  "memory.token_merge_mlp.0", "memory.token_merge_mlp.2"
]

## dataset
dataset: qwenmem_nframes_8
template: qwen2_vl
cutoff_len: 16384
max_samples: 1000
overwrite_cache: false
preprocessing_num_workers: 16
dataloader_num_workers: 2

## output
output_dir: saves/qwen2_5vl-3b/sft/nframes_8
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

## train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500