## model 
model_name_or_path: /projects/vig/tangri/QwenMem/LLaMA-Factory/models/Qwen2_5_VL-3B-WithMemory
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

## method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,k_proj,v_proj,o_proj
additional_target: token_merge_ln_q, vgg_to_language_ln_q, vgg_to_language_mlp_1, vgg_to_language_gelu, vgg_to_language_mlp_2, token_merge_mlp_1, token_merge_gelu, token_merge_mlp_2, decoder_embed_state, decoder_embed_visual
deepspeed: /projects/vig/tangri/QwenMem/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

## dataset
dataset: qwenmem_nframes_16
template: qwen2_vl
cutoff_len: 16384
overwrite_cache: false
preprocessing_num_workers: 8
dataloader_num_workers: 2

## output
output_dir: saves/qwen2_5vl-3b/sft/memory/nframes_16
logging_steps: 5
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

## train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500